version: '3'
services:
  server:
    build: .
    depends_on:
    - redis
    ports:
    - 8080:8080
    environment:
      APP_WEATHERAPI_KEY: ${API_KEY}
      APP_CACHE_ADDRESS: redis:6379
  redis:
    image: redis:latest
    ports:
    - 6379:6379

