// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import context "context"
import mock "github.com/stretchr/testify/mock"
import weather "github.com/aszecowka/QWRhbSBTemVjb3drYSByZWNydWl0bWVudCB0YXNr/internal/weather"

// BulkGetter is an autogenerated mock type for the BulkGetter type
type BulkGetter struct {
	mock.Mock
}

// GetWeatherForCities provides a mock function with given fields: ctx, cities
func (_m *BulkGetter) GetWeatherForCities(ctx context.Context, cities []string) (map[string]*weather.OpenWeatherResponse, error) {
	ret := _m.Called(ctx, cities)

	var r0 map[string]*weather.OpenWeatherResponse
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]*weather.OpenWeatherResponse); ok {
		r0 = rf(ctx, cities)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*weather.OpenWeatherResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, cities)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
